### ISSUE TITLE
--region="global" leads to `ValueError: 'global' is not in list`

### ISSUE THREAD

**Issue by manorman5** [jrising/prospectus-tools#34]
This is an issue Rae is having. I think [get_regions](https://github.com/jrising/prospectus-tools/blob/4d5244267cfa5e71192a6719086c6cf3bdd58156/gcp/extract/lib/configs.py#L195) needs the following slight modification:
```
def get_regions(config, allregions):
    """Grab and parse regions to extract from file
    This handles the specification of the desired regions. Both a
    `region` (a single region as a string) and `regions` (a list of
    region names) config argument are supported, as well as some key
    names within the regions list: 'global', 'countries', and 'funds'.
    Parameters
    ----------
    config : dict
    allregions : Sequence of str
        Regions available for extraction in the target NetCDF file.
    Returns
    -------
    Iterable
    """
    if 'region' in config:
        if config['region'] == 'global':
            return ['']
        return [config['region']]
    regions = config.get('regions', allregions)
    if 'global' in regions:
        regions = ['' if x == 'global' else x for x in regions]
    if 'countries' in regions:
        regions = filter(lambda x: x != 'countries', regions) + filter(lambda x: len(x) == 3, allregions)
    if 'funds' in regions:
        regions = filter(lambda x: x != 'funds', regions) + filter(lambda x: x[:5] == 'FUND-', allregions)
    return regions
```

Rae let me know if the above modification doesn't fix your problem. I thought I'd move the conversation here with the hopes that its a better place to document quantiles.py debugging for future RA debugging efforts. If people don't like me putting this very small issue here happy to delete it.

**Comment by ruixue-li** [comment]
Thanks Maya! The fix is working so far! I'll see if it finishes running and gets  
I guess if this is the issue, then we can also modify `load_median.R` to put `--regions=['']` if it sees `global` as the region specified (which I tried and it works the same way as your modification). 
Do you think it's better to change the `get_regions` function here instead?

**Comment by jrising** [comment]
I think there is a better way to solve this problem, since you've started to reproduce the logic that already exists for the `regions` (with an `s`) config option. Start by collecting either `config['region']` or `config['regions']`, and put it into a `regions` variable. Like this:
```
    if 'region' in config:
        regions = [config['region']]
    else:
        regions = config.get('regions', allregions)
```
And then you can keep the rest of the function, starting with `if 'global' in regions:`.

Can you make this change and put it in a pull request? Thanks!

**Comment by manorman5** [comment]
Cool yep, that's better thanks @jrising!.  

@ruixue-li Changing the `get_regions` function is a better fix I think. Here's my reasoning: I found it confusing that you could use the `global` keyword with the `regions` parameter, but not with `region` parameter. It also seemed like that wasn't the intention, but I could be wrong. Anyways, to avoid a future user tripping up on this quirk I thought changing the code upstream of load_median.R would be better. If you agree, would you prefer I file the PR or do you want to?

**Comment by ruixue-li** [comment]
Thank you so much @mayaanorman @jrising ! 

I've tested James' modification and will submit a pull request, but it seems that I need permission to push to this repo. Maybe either @jrising or @brews can give me permission? Thanks!

**Comment by jrising** [comment]
@ruixue-li No problem, I've invited you.
